print("      ~~HACKER SIMULATOR~~    ")
print("1-WIFI HACK")
cevap = int(input("choose an action >>>"))
if cevap == 1:
  print("You chose the 1st transaction ")
cevap = input("WIFI NAME ? >>> ")

import time
time.sleep(1)
print("starts hacking...")
time.sleep(0.3)
print("%1")
time.sleep(0.3)
print("%15")
time.sleep(0.3)
print("%20")
time.sleep(0.3)
print("%25")
time.sleep(0.3)
print("%30")
time.sleep(0.3)
print("%35")
time.sleep(0.5)
print("%47")
time.sleep(0.4)
print("%51")
time.sleep(0.2)
print("%60")
time.sleep(0.9)
print("%63")
time.sleep(0.6)
print("%78")
time.sleep(0.3)
print("%80")
time.sleep(0.3)
print("%85")
time.sleep(0.1)
print("%90")
time.sleep(0.8)
print("%97")
time.sleep(0.7)
print("%99")
time.sleep(1)
print("%100")

print("PASSWORD FOUND")
time.sleep(2)
print("password/ ms14ye22")
time.sleep(1)
print("Ip/ 192.168.8.5")
print("                    ")
print("Stop plaseee ")
input("can you give me 1 star before you leave :) >")
print("okayy take care of yourself :) ")
